# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'unimp', :subspecs => [
        'Core',  
        'Audio',              ##音频
        'File',
        'Geolocation',        ##系统定位
        'Camera&Gallery',     ##相机&相册
        'Geolocation-Gaode',
        'Map-Gaode', 
        # 'Payment-IAP',       ##苹果内购
      #  'Payment-AliPay',     ##支付宝支付
      #  'Oauth-Apple',        ##苹果登录
      #  'Oauth-QQ',           ##QQ登录
       #  'Payment-Wechat',     ##微信支付-同时使用微信分享或登录,必需使用包含支付的依赖库
      #  'Oauth-Wechat',       ##微信登录-包含支付
      #  'Oauth-Wechat-Nopay', ##微信登录-不包含支付
  ]
  pod 'SSZipArchive'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
