name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.json'

jobs:
  build:
    name: build apk
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: "Set up Flutter '3.24.3'"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'
      - name: "download flutter dependencies"
        run: flutter pub get
      - name: "flutter apk build"
        run: flutter build apk --release --target-platform=android-arm64 --no-shrink
      - name: "check result"
        run: ll
  apk:
    name: Generate APK
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'
      - run: flutter build apk --release --target-platform=android-arm64 --no-shrink
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
